// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateVideoInput struct {
	Title       string `json:"title" bson:"title"`
	Description string `json:"description" bson:"description"`
	UserID      int    `json:"userId" bson:"userId"`
	Source      string `json:"source" bson:"source"`
}

type DeleteVideoInput struct {
	ID string `json:"id" bson:"_id"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateVideoInput struct {
	Title       *string `json:"title,omitempty" bson:"title"`
	Description *string `json:"description,omitempty" bson:"description"`
	UserID      *int    `json:"userId,omitempty" bson:"userId"`
	Source      *string `json:"source,omitempty" bson:"source"`
}

type Video struct {
	ID          string    `json:"_id" bson:"_id"`
	Title       string    `json:"title" bson:"title"`
	Description string    `json:"description" bson:"description"`
	Source      string    `json:"source" bson:"source"`
	UserID      int       `json:"userId" bson:"userId"`
	CreatedAt   time.Time `json:"createdAt" bson:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt" bson:"updatedAt"`
}
