// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateVideoInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	UserID      int    `json:"userId"`
}

type DeleteVideoInput struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateVideoInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	UserID      *int    `json:"userId,omitempty"`
}

type Video struct {
	ID          string `json:"_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	UserID      int    `json:"userId"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}
